### ISSUE TITLE
Assign widget work for each member

### ISSUE THREAD

**Issue by jrd404** [tigris-fec/fec-greenfield#14]
> Clarification on meaning? (Jarrod)

**Comment by jrd404** [comment]
@tonyguo665 Clarification on meaning here? Please close out otherwise.

**Comment by tonyguo665** [comment]
**OVERVIEW: JARROD**
**QUESTIONS AND ANSWERS: ZAID**
**RELATED PRODUCTS: TONY**
**RATINGS AND REVIEWS: TEAM**
